global:
  scrape_interval:     1s
  evaluation_interval: 1s

rule_files:
scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 1s 
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          group: 'cadvisor'
          
  - job_name: 'server-1_metrics'
    scrape_interval: 1s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['server-1:8000']
        labels:
          group: 'fl_server'
          node: 'server-1'
          
  - job_name: 'server-2_metrics'
    scrape_interval: 1s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['server-2:8000']
        labels:
          group: 'fl_server'
          node: 'server-2'
          
  - job_name: 'server-3_metrics'
    scrape_interval: 1s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['server-3:8000']
        labels:
          group: 'fl_server'
          node: 'server-3' 